#pragma once

enum BlockSoundEvent {
	BLOCK_SOUND_EVENT_WOOD_BREAK,
	BLOCK_SOUND_EVENT_WOOD_STEP,
	BLOCK_SOUND_EVENT_WOOD_PLACE,
	BLOCK_SOUND_EVENT_WOOD_HIT,
	BLOCK_SOUND_EVENT_WOOD_FALL,

	BLOCK_SOUND_EVENT_GRAVEL_BREAK,
	BLOCK_SOUND_EVENT_GRAVEL_STEP,
	BLOCK_SOUND_EVENT_GRAVEL_PLACE,
	BLOCK_SOUND_EVENT_GRAVEL_HIT,
	BLOCK_SOUND_EVENT_GRAVEL_FALL,

	BLOCK_SOUND_EVENT_GRASS_BREAK,
	BLOCK_SOUND_EVENT_GRASS_STEP,
	BLOCK_SOUND_EVENT_GRASS_PLACE,
	BLOCK_SOUND_EVENT_GRASS_HIT,
	BLOCK_SOUND_EVENT_GRASS_FALL,

	BLOCK_SOUND_EVENT_STONE_BREAK,
	BLOCK_SOUND_EVENT_STONE_STEP,
	BLOCK_SOUND_EVENT_STONE_PLACE,
	BLOCK_SOUND_EVENT_STONE_HIT,
	BLOCK_SOUND_EVENT_STONE_FALL,

	BLOCK_SOUND_EVENT_METAL_BREAK,
	BLOCK_SOUND_EVENT_METAL_STEP,
	BLOCK_SOUND_EVENT_METAL_PLACE,
	BLOCK_SOUND_EVENT_METAL_HIT,
	BLOCK_SOUND_EVENT_METAL_FALL,

	BLOCK_SOUND_EVENT_GLASS_BREAK,
	BLOCK_SOUND_EVENT_GLASS_STEP,
	BLOCK_SOUND_EVENT_GLASS_PLACE,
	BLOCK_SOUND_EVENT_GLASS_HIT,
	BLOCK_SOUND_EVENT_GLASS_FALL,

	BLOCK_SOUND_EVENT_CLOTH_BREAK,
	BLOCK_SOUND_EVENT_CLOTH_STEP,
	BLOCK_SOUND_EVENT_CLOTH_PLACE,
	BLOCK_SOUND_EVENT_CLOTH_HIT,
	BLOCK_SOUND_EVENT_CLOTH_FALL,

	BLOCK_SOUND_EVENT_SAND_BREAK,
	BLOCK_SOUND_EVENT_SAND_STEP,
	BLOCK_SOUND_EVENT_SAND_PLACE,
	BLOCK_SOUND_EVENT_SAND_HIT,
	BLOCK_SOUND_EVENT_SAND_FALL,

	BLOCK_SOUND_EVENT_SNOW_BREAK,
	BLOCK_SOUND_EVENT_SNOW_STEP,
	BLOCK_SOUND_EVENT_SNOW_PLACE,
	BLOCK_SOUND_EVENT_SNOW_HIT,
	BLOCK_SOUND_EVENT_SNOW_FALL,

	BLOCK_SOUND_EVENT_LADDER_BREAK,
	BLOCK_SOUND_EVENT_LADDER_STEP,
	BLOCK_SOUND_EVENT_LADDER_PLACE,
	BLOCK_SOUND_EVENT_LADDER_HIT,
	BLOCK_SOUND_EVENT_LADDER_FALL,

	BLOCK_SOUND_EVENT_ANVIL_BREAK,
	BLOCK_SOUND_EVENT_ANVIL_STEP,
	BLOCK_SOUND_EVENT_ANVIL_PLACE,
	BLOCK_SOUND_EVENT_ANVIL_HIT,
	BLOCK_SOUND_EVENT_ANVIL_FALL,

	BLOCK_SOUND_EVENT_SLIME_BREAK,
	BLOCK_SOUND_EVENT_SLIME_STEP,
	BLOCK_SOUND_EVENT_SLIME_PLACE,
	BLOCK_SOUND_EVENT_SLIME_HIT,
	BLOCK_SOUND_EVENT_SLIME_FALL,
};					 