#pragma once

enum DyeColors {
	ENUM_DYE_COLOR_WHITE,
    ENUM_DYE_COLOR_ORANGE,
    ENUM_DYE_COLOR_MAGENTA,
    ENUM_DYE_COLOR_LIGHT_BLUE,
    ENUM_DYE_COLOR_YELLOW,
    ENUM_DYE_COLOR_LIME,
    ENUM_DYE_COLOR_PINK,
    ENUM_DYE_COLOR_GRAY,
    ENUM_DYE_COLOR_SILVER,
    ENUM_DYE_COLOR_CYAN,
    ENUM_DYE_COLOR_PURPLE,
    ENUM_DYE_COLOR_BLUE,
    ENUM_DYE_COLOR_BROWN,
    ENUM_DYE_COLOR_GREEN,
    ENUM_DYE_COLOR_RED,
    ENUM_DYE_COLOR_BLACK
};